/**
 * Check if the attendance records are complete and send emails if they aren't.
 */

function attemptToCheckResponses() {
  try {
    checkForIncompleteResponses();
  } catch (err) {
    emailError(err, 'checkForIncompleteResponses', 'n/a');
  }
}

function checkForIncompleteResponses() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const processSheet = ss.getSheetByName(c.PROCESS_SHEET);

  const lastRow = processSheet.getRange(c.PROCESS_LAST_ROW_CELL[0], c.PROCESS_LAST_ROW_CELL[1]).getValue();
  const lastConfirmedRow = processSheet.getRange(c.PROCESS_LAST_CONFIRMED_CELL[0], c.PROCESS_LAST_CONFIRMED_CELL[1]).getValue();

  let nameValue, dateValue, startDisplayValue, endDisplayValue, lengthValue, statusCell, emailDateCell;
  const now = new Date();

  for (i = lastConfirmedRow; i < lastRow + 1; i++) {
    nameValue = processSheet.getRange(i, c.PROCESS_NAME_COL).getValue();
    dateValue = processSheet.getRange(i, c.PROCESS_DATE_COL).getValue();
    startDisplayValue = processSheet.getRange(i, c.PROCESS_START_COL).getDisplayValue();
    endDisplayValue = processSheet.getRange(i, c.PROCESS_END_COL).getDisplayValue();
    lengthValue = processSheet.getRange(i, c.PROCESS_LEN_COL).getValue();
    statusCell = processSheet.getRange(i, c.PROCESS_STATUS_COL);
    emailDateCell = processSheet.getRange(i, c.PROCESS_EMAIL_TIME_COL);

    // if the cell is confirmed or no correction or has no name
    if (statusCell.getValue() == c.SessionStatus.Confirmed || 
      statusCell.getValue() == c.SessionStatus.NoCorrection ||
      nameValue == "") {
      console.log(`skipped row ${i} of ${lastRow}`);
      continue;
    }

    if (statusCell.getValue() == c.SessionStatus.Incomplete) {
      let shouldNotTimeout = now - emailDateCell.getValue() <= c.TIMEOUT_VALUE;
      if (shouldNotTimeout) {
        console.log(`tried to time out row ${i} of ${lastRow} but was within the timeout range`);
        continue;
      } else {
        console.log(`timed out row ${i} of ${lastRow}`);
        statusCell.setValue(c.SessionStatus.NoCorrection);
        continue;
      }
    }

    // if the entry has has been timed out
    if (statusCell.getValue() == c.SessionStatus.Pending) {
      if (lengthValue != "") {
        statusCell.setValue(c.SessionStatus.Confirmed);
      }

      if (startDisplayValue != "" && endDisplayValue != "") {
        throw new Error(`length missing but had both start and end cell for row ${i}`);
      }

      sendForCorrection(nameValue, dateValue, startDisplayValue, endDisplayValue);
      statusCell.setValue(c.SessionStatus.Incomplete);
      emailDateCell.setValue(Utilities.formatDate(now, c.TIMEZONE, c.DATE_TIME_FORMAT));
    }
  }
}

function sendForCorrection(name, date, start, end) {
  const formattedDate = Utilities.formatDate(date, c.TIMEZONE, c.DATE_WEEKDAY_FORMAT);

  const whichWasForgotten = start ? "sign out" : "sign in";
  const prefilledCorrectionsFormUrl = getPreFilledFormLink(name, date, whichWasForgotten, start, end);

  const emailSubject = 'Robotics Attendance Incomplete - Alert';
  const emailBody = `Hello! <br> <br>
    At the robotics session on ${formattedDate}, <b>you forgot to ${whichWasForgotten}</b>. You can regain 
    the hours by completing the form below: 
    <br><br><a href=${prefilledCorrectionsFormUrl}>LINK TO FORM</a> <br><br>
    If you do not complete this form within 23 hours, you will not gain hours for that session. If you have 
    any questions, please reach out to Mr. Ali. Happy roboting!
    <br> <br> <br>
    This email was auto-generated by the attendance tracker using the following information: <br><br>
    Name: ${name} <br>
    Session date: ${formattedDate} <br>
    Sign in time: ${start} <br>
    Sign out time: ${end} <br>
    `;

  emailStudent(name, emailSubject, emailBody);
}
