/**
 * This script will send an email if an attendance record is incomplete. 
 * Process: 
 * - Checks if there are any inconsistent entries within the last 24 hours 
 * - Emails relevant person with a link to a form for correcting hours
 */


/** Check if there are any incomplete responses. */
function checkForIncompleteResponses() {
  try {
    performTheCheck(); 
  } catch (err) {
    emailError(err, "checkForIncompleteResponses"); 
  }
}

/** Check for incomplete responeses */
function performTheCheck() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const processSheet = ss.getSheetByName(PROCESS_SHEET);
  const now = Utilities.formatDate(new Date(), 'Europe/London', 'dd/MM HH:mm');

  const last_row = processSheet.getRange(1, 12).getValue();
  const last_confirmed_row = processSheet.getRange(1, 10).getValue(); 
  var new_confirmed_last_row = last_confirmed_row; 

  for (i = last_confirmed_row; i < last_row + 1; i++) {
    console.log(`checkForIncompleteResponses: checking row ${i} of ${last_row}`); 

    let confirmed_cell = processSheet.getRange(i, 6);
    let date_cell = processSheet.getRange(i, 7);

    // if the row has already been confirmed or if there is no name
    if(confirmed_cell.getValue() == "confirmed" || confirmed_cell.getValue() == "no correction" || processSheet.getRange(i, 1).getValue() == "") {
      console.log(`${i} of ${last_row}: confirmed or no correction`);
      if (i - new_confirmed_last_row <= 1) {
        new_confirmed_last_row = i; 
      }
      continue; 
    }

    // if the row is confirming and it's been more than 23 hours since the email was sent
    if(confirmed_cell.getValue() == CORRECTING_STATUS) {
      console.log(`${i} of ${last_row}: email already sent`);
      // check if it's been more than 23 hours since the email was sent
      const now = new Date()
      if (now.getTime() - date_cell.getValue() > 1000 * 60 * 60 * 23) {
        console.log(`${i} of ${last_row}: changed to no correction`);
        confirmed_cell.setValue("no correction"); 
      } 
    
    // check if the entry is incomplete
    } else if(processSheet.getRange(i, 5).getValue() == "") {
      console.log(`${i} of ${last_row}: missing session length`);

      let name = processSheet.getRange(i, 1).getValue(); 
      let timestamp = processSheet.getRange(i, 2).getValue(); 
      let start_time = processSheet.getRange(i, 3).getValue(); 
      let end_time = processSheet.getRange(i, 4).getValue(); 

      if (start_time != "" && end_time != "") {
        console.log(`not both start and end time were empty; row ${i}`); 
        continue; 
      }

      // they did not do one of the two 
      sendForCorrection(name, timestamp, start_time, end_time); 
      confirmed_cell.setValue(CORRECTING_STATUS);
      date_cell.setValue(now); 
    } else {
      // there was a length 
      console.log(`${i} of ${last_row}: changed to confirmed`);
      confirmed_cell.setValue('confirmed'); 
    }
  }

  processSheet.getRange(1, 10).setValue(new_confirmed_last_row); 

}

/** Email someone if they have an incomplete session */
function sendForCorrection(name, timestamp, start_time, end_time) {
  let email_address = getEmailAddress(name); 
  const email_subject = 'Robotics Attendance Incomplete - Alert'; 
  let formatted_date = ""
  let formatted_start_time = ""; 
  let formatted_end_time = ""; 

  // checks that the dates exist
  if (timestamp != "") {
    formatted_date = Utilities.formatDate(timestamp, 'Europe/London', 'EEEEE, MMM d'); 
  }
  if(start_time != "") {
    formatted_start_time = Utilities.formatDate(start_time, 'Europe/London', 'HH:mm'); 
  } else if (end_time != "") {
    formatted_end_time = Utilities.formatDate(end_time, 'Europe/London', 'HH:mm');
  }

  const sign_in = start_time == "" ? "sign in" : "sign out"; 
  
  const email_body = `Hello! <br> <br>
    At the robotics session on ${formatted_date}, <b>you forgot to ${sign_in}</b>. You can regain the hours by completing 
    the form below: 
    <br><br><a href=${CORRECTION_FORM_URL}>LINK TO FORM</a> <br><br>
    If you do not complete this form within 23 hours, you will not gain hours for that session. If you have any questions, 
    please reach out to Mr. Ali. Happy roboting!
    <br> <br> <br>
    This email was auto-generated by the attendance tracker using the following information: <br><br>
    Name: ${name} <br>
    Session date: ${formatted_date} <br>
    Sign in time: ${formatted_start_time} <br>
    Sign out time: ${formatted_end_time} <br>
    `; 

  // send the reminder email 
  GmailApp.sendEmail(
    email_address, 
    email_subject, 
    "", 
    { name: 'ASL Robotics', 
      htmlBody: email_body, 
    }
  );

}

/** get the person's email address */
function getEmailAddress(name) {
  const ss = SpreadsheetApp.getActiveSpreadsheet(); 
  const emailSheet = ss.getSheetByName(TEAM_SHEET_NAME);

  const last_row = emailSheet.getLastRow(); 

  for (let j = 1; j < last_row + 1; j++) {
    if (emailSheet.getRange(j, 1).getValue() == name) {
      return emailSheet.getRange(j, 3).getValue(); 
    }
  }

  return 'mackensiesemail@gmail.com'; 
}

